import { NextResponse } from "next/server";
import { doc, serverTimestamp, setDoc } from "firebase/firestore";
import { db } from "../../../lib/firebase";

export async function GET() {
  try {
    const items = [
      {
        id: "SGN-HAN-2026-04-19-SPQ-0630",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Sun Phu Quoc Airways",
        airlineCode: "SPQ",
        airlineLogo: "/airlines/sunphuquoc.png",
        flightNumber: "9G808",
        aircraft: "Airbus 321",
        departTime: "06:30",
        arriveTime: "08:40",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Tất cả",
        price: 2761000,
        seatsLeft: 3,
        baggageText: "",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2711K",
        active: true,
        featured: true,
      },
      {
        id: "SGN-HAN-2026-04-19-VJ-0605",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietjet Air",
        airlineCode: "VJ",
        airlineLogo: "/airlines/vietjet.png",
        flightNumber: "VJ124",
        aircraft: "Airbus 320",
        departTime: "06:05",
        arriveTime: "08:15",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2792600,
        seatsLeft: 23,
        baggageText: "Đã bao gồm hành lí xách tay 7 kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2742.6K",
        active: true,
        featured: false,
      },
      {
        id: "SGN-HAN-2026-04-19-VJ-0730",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietjet Air",
        airlineCode: "VJ",
        airlineLogo: "/airlines/vietjet.png",
        flightNumber: "VJ126",
        aircraft: "Airbus 321",
        departTime: "07:30",
        arriveTime: "09:40",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2792600,
        seatsLeft: 30,
        baggageText: "Đã bao gồm hành lí xách tay 7 kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2742.6K",
        active: true,
        featured: false,
      },
      {
        id: "SGN-HAN-2026-04-19-VJ-0840",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietjet Air",
        airlineCode: "VJ",
        airlineLogo: "/airlines/vietjet.png",
        flightNumber: "VJ130",
        aircraft: "Airbus 321",
        departTime: "08:40",
        arriveTime: "10:50",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2792600,
        seatsLeft: 18,
        baggageText: "Đã bao gồm hành lí xách tay 7 kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2742.6K",
        active: true,
        featured: false,
      },
      {
        id: "SGN-HAN-2026-04-19-VJ-1200",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietjet Air",
        airlineCode: "VJ",
        airlineLogo: "/airlines/vietjet.png",
        flightNumber: "VJ136",
        aircraft: "Airbus 320",
        departTime: "12:00",
        arriveTime: "14:10",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2792600,
        seatsLeft: 2,
        baggageText: "Đã bao gồm hành lí xách tay 7 kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2742.6K",
        active: true,
        featured: false,
      },
      {
        id: "SGN-HAN-2026-04-19-VJ-1615",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietjet Air",
        airlineCode: "VJ",
        airlineLogo: "/airlines/vietjet.png",
        flightNumber: "VJ148",
        aircraft: "Airbus 320",
        departTime: "16:15",
        arriveTime: "18:25",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2792600,
        seatsLeft: 8,
        baggageText: "Đã bao gồm hành lí xách tay 7 kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2742.6K",
        active: true,
        featured: false,
      },
      {
        id: "SGN-HAN-2026-04-19-VJ-1645",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietjet Air",
        airlineCode: "VJ",
        airlineLogo: "/airlines/vietjet.png",
        flightNumber: "VJ146",
        aircraft: "Airbus 321",
        departTime: "16:45",
        arriveTime: "18:55",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2792600,
        seatsLeft: 4,
        baggageText: "Đã bao gồm hành lí xách tay 7 kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2742.6K",
        active: true,
        featured: false,
      },
      {
        id: "SGN-HAN-2026-04-19-VJ-1710",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietjet Air",
        airlineCode: "VJ",
        airlineLogo: "/airlines/vietjet.png",
        flightNumber: "VJ152",
        aircraft: "Airbus 321",
        departTime: "17:10",
        arriveTime: "19:20",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2792600,
        seatsLeft: 13,
        baggageText: "Đã bao gồm hành lí xách tay 7 kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2742.6K",
        active: true,
        featured: false,
      },
      {
        id: "SGN-HAN-2026-04-19-VJ-1740",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietjet Air",
        airlineCode: "VJ",
        airlineLogo: "/airlines/vietjet.png",
        flightNumber: "VJ150",
        aircraft: "Airbus 321",
        departTime: "17:40",
        arriveTime: "19:50",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2792600,
        seatsLeft: 16,
        baggageText: "Đã bao gồm hành lí xách tay 7 kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2742.6K",
        active: true,
        featured: false,
      },
      {
        id: "SGN-HAN-2026-04-19-BB-1045",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Bamboo Airways",
        airlineCode: "BB",
        airlineLogo: "/airlines/bamboo.png",
        flightNumber: "QH240",
        aircraft: "Airbus 320",
        departTime: "10:45",
        arriveTime: "12:55",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2868000,
        seatsLeft: 1,
        baggageText: "Đã bao gồm hành lí xách tay 7 kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2818K",
        active: true,
        featured: false,
      },
      {
        id: "SGN-HAN-2026-04-19-VU-0545",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietravel Airlines",
        airlineCode: "VU",
        airlineLogo: "/airlines/vietravel.png",
        flightNumber: "VU750",
        aircraft: "Airbus 321",
        departTime: "05:45",
        arriveTime: "07:55",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2974040,
        seatsLeft: 8,
        baggageText: "Đã bao gồm hành lí xách tay 7kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2924.04K",
        active: true,
        featured: false,
      },
      {
        id: "SGN-HAN-2026-04-19-VU-1710",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "HAN",
        toLabel: "Hà Nội (HAN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietravel Airlines",
        airlineCode: "VU",
        airlineLogo: "/airlines/vietravel.png",
        flightNumber: "VU780",
        aircraft: "Airbus 321",
        departTime: "17:10",
        arriveTime: "19:20",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2974040,
        seatsLeft: 8,
        baggageText: "Đã bao gồm hành lí xách tay 7kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K chỉ còn 2924.04K",
        active: true,
        featured: false,
      },

      {
        id: "HAN-SGN-2026-04-19-VJ-0615",
        fromCode: "HAN",
        fromLabel: "Hà Nội (HAN)",
        toCode: "SGN",
        toLabel: "Hồ Chí Minh (SGN)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietjet Air",
        airlineCode: "VJ",
        airlineLogo: "/airlines/vietjet.png",
        flightNumber: "VJ181",
        aircraft: "Airbus 321",
        departTime: "06:15",
        arriveTime: "08:25",
        durationText: "2h10m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 2812600,
        seatsLeft: 21,
        baggageText: "Đã bao gồm hành lí xách tay 7 kg",
        promoText: "Nhập mã MBFDLV giảm ngay 50K",
        active: true,
        featured: false,
      },
      {
        id: "HAN-DAD-2026-04-19-VN-0700",
        fromCode: "HAN",
        fromLabel: "Hà Nội (HAN)",
        toCode: "DAD",
        toLabel: "Đà Nẵng (DAD)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietnam Airlines",
        airlineCode: "VN",
        airlineLogo: "/airlines/vietnam-airlines.png",
        flightNumber: "VN171",
        aircraft: "Airbus 321",
        departTime: "07:00",
        arriveTime: "08:25",
        durationText: "1h25m",
        stopsText: "Bay thẳng",
        cabin: "Tất cả",
        price: 1980000,
        seatsLeft: 14,
        baggageText: "Đã bao gồm hành lí xách tay 12 kg",
        promoText: "",
        active: true,
        featured: false,
      },
      {
        id: "SGN-DAD-2026-04-19-VJ-0900",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "DAD",
        toLabel: "Đà Nẵng (DAD)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietjet Air",
        airlineCode: "VJ",
        airlineLogo: "/airlines/vietjet.png",
        flightNumber: "VJ620",
        aircraft: "Airbus 320",
        departTime: "09:00",
        arriveTime: "10:20",
        durationText: "1h20m",
        stopsText: "Bay thẳng",
        cabin: "Phổ thông",
        price: 1450000,
        seatsLeft: 11,
        baggageText: "Đã bao gồm hành lí xách tay 7 kg",
        promoText: "",
        active: true,
        featured: false,
      },
      {
        id: "SGN-PQC-2026-04-19-VN-1030",
        fromCode: "SGN",
        fromLabel: "Hồ Chí Minh (SGN)",
        toCode: "PQC",
        toLabel: "Phú Quốc (PQC)",
        departDate: "2026-04-19",
        tripType: "oneway",
        airline: "Vietnam Airlines",
        airlineCode: "VN",
        airlineLogo: "/airlines/vietnam-airlines.png",
        flightNumber: "VN1827",
        aircraft: "Airbus 321",
        departTime: "10:30",
        arriveTime: "11:35",
        durationText: "1h05m",
        stopsText: "Bay thẳng",
        cabin: "Tất cả",
        price: 1320000,
        seatsLeft: 9,
        baggageText: "Đã bao gồm hành lí xách tay 12 kg",
        promoText: "",
        active: true,
        featured: false,
      },
    ];

    for (const item of items) {
      await setDoc(
        doc(db, "flight_search_items", item.id),
        {
          ...item,
          createdAt: serverTimestamp(),
          updatedAt: serverTimestamp(),
        },
        { merge: true }
      );
    }

    return NextResponse.json({
      ok: true,
      message: `Seed thành công ${items.length} chuyến bay`,
      total: items.length,
    });
  } catch (error) {
    console.error("Seed flight search error:", error);

    return NextResponse.json(
      {
        ok: false,
        message: "Seed dữ liệu chuyến bay thất bại",
        error: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}